spring:
  config:
    import: file:certs/application-local-ssl.yaml


server:
  ssl:
    bundle: "server"
    enabled-protocols: TLSv1.3

application:
  allowed-origins: https://localhost:9811,https://localhost:9810
