spring:
  config:
    import: file:certs/application-prod-ssl.yaml

server:
  ssl:
    bundle: "server"
    enabled-protocols: TLSv1.3

application:
  allowed-origins: https://balage-srv.ddns.net:9810

