server:
  shutdown: graceful
  port: 9810

rsa:
  private-key: classpath:certs/private-key-2.pem
  public-key: classpath:certs/public-key.pem


spring:
  application:
    name: Yasp!

  servlet:
    multipart:
      max-file-size: 3MB
  
  lifecycle:
    timeout-per-shutdown-phase: 60s

#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/homeworkmole
#    username: homeworkmole
#    password: h0m3w0rkm0l3
#    driverClassName: org.postgresql.Driver
#    tomcat:
#      initial-size: 5
#      max-wait: 300000
#      max-active: 50
#      max-idle: 5
#      min-idle: 2
#      default-auto-commit: true
#      test-on-borrow: true
#      validation-query: SELECT 1

#  jpa:
#    open-in-view: true
#    #    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        envers:
#          autoRegisterListeners: false
#          store_data_at_delete: true
#        format_sql: true
#        use_sql_comments: true
#    show-sql: true

#  mail:
#    default-encoding: UTF-8

#  flyway:
#    locations: classpath:hu/vissy/homeworkmole/migration,classpath:/sql

#  mvc:
#    static-path-pattern: /frontend/**

#  web:
#    resources:
#      static-locations: classpath:/frontend/

logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: debug

homeworkmole:
  public-url: http://localhost:9811/#/
  email:
    from: tanacsadas@pmi.co.hu
    internal: vissy.balazs@pmi.co.hu
    service:
      frequency: 5000
  node:
    search.limit: 50

application:
  allowed-origins: http://localhost:9811,http://localhost:9810,http://192.168.1.128:9811,http://192.168.1.128:9810,http://balage-srv.ddns.net:9811,http://192.168.1.193:9811,http://balage-srv.ddns.net:9810,http://192.168.1.193:9810

fileStore:
  #  fileKeyProvider: "hu.vissy.filestore.SequentialFileKeyProvider"
  fileKeyProvider: "hu.vissy.filestore.HashedFileKeyProvider"
  pathSplitter:
    storeDirectory: filestore
    extension: data
    useFullKeyOnName: true
    pathSplit: '3/3/3'